package com.xyazh.kanake.render.shader;

public class ShaderDisSources {
    public static final String vertexShaderSource = "#version 330 core\n"
        + "layout(location = 0) in vec3 a_pos;\n"
        + "layout(location = 1) in vec4 a_color;\n"
        + "layout(location = 2) in vec2 a_tex_coord;\n"
        + "layout(location = 3) in vec3 a_normal;\n"
        + "out vec2 tex_coord;\n"
        + "out vec4 solor;\n"
        + "out vec3 normal;\n"
        + "out vec4 world_pos;\n"
        + "uniform mat4 dm1;\n"
        + "void main()\n"
        + "{\n"
        + "world_pos = dm1*vec4(a_pos.x, a_pos.y, a_pos.z, 1.0);\n"
        + "tex_coord = a_tex_coord;\n"
        + "solor = a_color;\n"
        + "normal = (vec4(a_normal,0) * dm1).xyz;\n"
        + "gl_Position = world_pos;\n"
        + "}";

    public static final String fragmentShaderSource = "#version 330 core\n"
            + "in vec2 tex_coord;\n"
            + "in vec4 solor;\n"
            + "in vec3 normal;\n"
            + "in vec4 world_pos;\n"
            + "out vec4 FragColor;\n"
            + "uniform sampler2D id;\n"
            + "uniform vec4 world_light;\n"
            + "uniform vec4 world_bright_light;\n"
            + "uniform vec4 world_directional_light_color;\n"
            + "uniform vec4 world_bright_directional_light_color;\n"
            + "uniform vec3 world_directional_light_vec;\n"
            + "void main()\n"
            + "{\n"
            + "float diffuse_factor = dot(normal, world_directional_light_vec);\n"
            + "vec4 a_world_directional_light;\n"
            + "vec4 a_world_bright_directional_light_color;\n"
            + "if(diffuse_factor>0){\n"
            + "a_world_directional_light = diffuse_factor*world_directional_light_color;\n"
            + "a_world_bright_directional_light_color = diffuse_factor*world_bright_directional_light_color;\n"
            + "}\n"
            + "else{\n"
            + "a_world_directional_light = vec4(0, 0, 0, 0);\n"
            + "a_world_bright_directional_light_color = vec4(0, 0, 0, 0);\n"
            + "}\n"
            + "FragColor =texture(id,tex_coord);\n"
            + "}";
}
